In [ ]:
import pandas as pd
import numpy as ny

In [ ]:
df = pd.read_csv('dataset_Facebook.csv' , sep=';')

In [ ]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [ ]:
df.shape

(500, 19)

In [ ]:
df["Type"].unique()

array(['Photo', 'Status', 'Link', 'Video'], dtype=object)

In [ ]:
df_photo = df[df["Type"]=="Photo"]
df_photo

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
df_status = df[df["Type"]=="Status"]
df_status

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
38,138895,Status,2,12,7,9,0.0,17576,33058,5352,5202,6547,23135,11792,4104,11,227.0,31.0,269
40,138895,Status,2,12,6,11,0.0,13280,24198,2055,1912,2720,17627,9344,1716,7,216.0,39.0,262
46,138353,Status,1,12,3,11,0.0,16576,30612,3572,3464,4802,24363,12888,3014,4,174.0,36.0,214
72,137893,Status,3,11,4,11,0.0,9056,16362,1006,847,1153,9562,5180,740,3,226.0,44.0,273
80,137177,Status,2,11,7,3,0.0,8728,17827,2295,2235,2828,15418,7344,2099,2,86.0,13.0,101
84,137177,Status,3,11,5,2,0.0,6692,13092,199,108,141,7549,3336,156,2,99.0,16.0,117
98,137020,Status,2,10,5,3,1.0,12468,24917,2143,1966,2576,15850,7636,1661,7,310.0,61.0,378
107,136736,Status,2,10,1,4,0.0,9504,19556,1132,1032,1512,16018,7616,981,17,193.0,28.0,238
109,136736,Status,2,10,7,3,0.0,13872,27468,2664,2570,3395,20198,10432,2252,4,217.0,50.0,271
121,136393,Status,2,10,7,9,0.0,15816,30514,2733,2654,3289,23584,11912,2361,6,186.0,40.0,232
138,136013,Status,2,10,5,3,0.0,8896,17202,1480,1426,1932,13838,7020,1292,0,129.0,25.0,154
141,136013,Status,3,10,3,10,0.0,13152,25666,2543,2438,3179,20547,10280,2278,2,227.0,36.0,265
142,136013,Status,2,10,3,2,1.0,31136,59964,6164,5934,9237,35977,18048,4376,60,859.0,90.0,1009
148,135713,Status,2,10,7,4,0.0,10744,20691,1967,1877,2201,17502,8964,1834,3,148.0,28.0,179
163,135617,Status,2,9,6,4,0.0,11096,21080,1843,1724,2106,16095,8120,1604,4,243.0,41.0,288
172,135195,Status,2,9,1,10,0.0,21256,41906,4840,4754,5906,35455,17592,4318,38,163.0,27.0,228
175,135195,Status,2,9,6,10,1.0,13216,24738,2675,2584,2969,19599,10232,2342,2,165.0,22.0,189
180,134879,Status,2,9,4,4,1.0,9124,17776,1476,1397,1797,13887,7092,1331,20,150.0,29.0,199
202,132817,Status,2,8,3,2,1.0,9236,16054,1151,1130,1560,14014,7880,1075,2,53.0,15.0,70
217,131956,Status,2,8,2,12,0.0,14424,26000,304,286,383,25539,14056,291,41,15.0,1.0,57
222,131808,Status,2,8,7,4,0.0,8260,14305,997,953,1211,12905,7360,956,1,74.0,11.0,86
223,131808,Status,2,8,6,10,1.0,20168,35904,3370,3244,5106,26881,15056,2806,18,332.0,54.0,404
225,131808,Status,2,7,5,14,0.0,15296,25269,2827,2781,3627,22103,13296,2602,9,95.0,17.0,121
232,131630,Status,2,7,2,6,1.0,10824,20573,135,126,153,20030,10384,126,6,14.0,1.0,21
235,131300,Status,2,7,7,10,0.0,10956,19279,128,119,130,18838,10564,123,3,13.0,1.0,17
242,130791,Status,2,7,4,6,0.0,17360,33613,2573,2448,6017,23338,11800,1905,9,484.0,79.0,572
253,129600,Status,2,7,5,12,1.0,15576,27513,2417,2327,3098,19078,10840,1839,11,238.0,51.0,300
267,128032,Status,2,7,5,10,0.0,10188,16978,1473,1441,2136,14450,8536,1395,13,61.0,13.0,87
275,126424,Status,2,7,3,13,0.0,18320,31448,3742,3682,7854,25584,14920,3300,36,98.0,14.0,148
282,126345,Status,2,6,7,11,0.0,12044,20327,2240,2193,3599,17717,10400,2119,0,104.0,13.0,117
285,126141,Status,2,6,6,4,0.0,8628,14847,870,843,1692,11970,6796,774,4,72.0,18.0,94
334,119198,Status,2,5,1,2,0.0,10152,17099,1636,1599,2755,15382,8980,1613,2,55.0,10.0,67
352,116435,Status,1,5,4,3,1.0,23832,42313,1701,1570,2838,37816,21352,1578,6,210.0,39.0,255
362,116091,Status,2,5,5,7,0.0,9232,16811,908,861,1967,12996,7200,843,1,129.0,36.0,166
371,113028,Status,2,4,6,3,1.0,17912,34774,2750,2567,6591,21009,11408,2256,17,447.0,123.0,587
416,104070,Status,1,3,3,15,0.0,9120,14759,951,937,1290,13246,8004,924,3,25.0,6.0,34

In [ ]:
df_photo.shape

(426, 19)

In [ ]:
df_status.shape

(45, 19)

In [ ]:
df_merge = pd.concat([df_photo,df_status])
df_merge

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,119198,Status,2,5,1,2,0.0,10152,17099,1636,1599,2755,15382,8980,1613,2,55.0,10.0,67
352,116435,Status,1,5,4,3,1.0,23832,42313,1701,1570,2838,37816,21352,1578,6,210.0,39.0,255
362,116091,Status,2,5,5,7,0.0,9232,16811,908,861,1967,12996,7200,843,1,129.0,36.0,166
371,113028,Status,2,4,6,3,1.0,17912,34774,2750,2567,6591,21009,11408,2256,17,447.0,123.0,587
416,104070,Status,1,3,3,15,0.0,9120,14759,951,937,1290,13246,8004,924,3,25.0,6.0,34

In [ ]:
df_merge.shape

(471, 19)

In [ ]:
df_sort = df.sort_values(by="like")
df_sort

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
417,104070,Photo,1,3,3,10,0.0,1874,2474,25,25,31,1483,1062,15,0,0.0,0.0,0
100,137020,Photo,1,10,4,9,1.0,1357,2453,37,37,55,2154,1120,32,0,0.0,0.0,0
76,137893,Photo,1,11,3,2,0.0,1228,2392,17,17,19,2392,1228,17,0,0.0,0.0,0
441,98195,Photo,1,3,5,4,1.0,1845,2670,9,9,9,1614,1008,9,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
349,117764,Photo,3,5,5,13,0.0,81856,124753,3000,1637,2718,52477,27392,1756,45,1639.0,122.0,1806
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
111,136736,Photo,1,10,6,8,0.0,1261,2158,37,37,49,1911,1077,33,0,NaN,NaN,0

In [ ]:
df_sort_comment = df.sort_values(by="comment" , ascending=False)

In [ ]:
df_sort_comment.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
288,126141,Photo,1,6,4,12,0.0,20896,29062,1418,1038,2048,19738,13656,998,103,469.0,33.0,605
228,131728,Photo,2,7,4,3,0.0,14824,21863,868,591,966,13498,8560,650,64,367.0,25.0,456

In [ ]:
df_transpose = df.transpose()
df_transpose

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [ ]:
df_melt = pd.melt(df)
df_melt

                variable   value
0       Page total likes  139441
1       Page total likes  139441
2       Page total likes  139441
3       Page total likes  139441
4       Page total likes  139441
...                  ...     ...
9495  Total Interactions      84
9496  Total Interactions      75
9497  Total Interactions     115
9498  Total Interactions     136
9499  Total Interactions     119

[9500 rows x 2 columns]

In [ ]:
df_melt1=pd.melt(df,id_vars=['Type','Category'],var_name='metrics',value_name='value')
df_melt1

        Type  Category             metrics     value
0      Photo         2    Page total likes  139441.0
1     Status         2    Page total likes  139441.0
2      Photo         3    Page total likes  139441.0
3      Photo         2    Page total likes  139441.0
4      Photo         2    Page total likes  139441.0
...      ...       ...                 ...       ...
8495   Photo         3  Total Interactions      84.0
8496   Photo         2  Total Interactions      75.0
8497   Photo         1  Total Interactions     115.0
8498   Photo         3  Total Interactions     136.0
8499   Photo         2  Total Interactions     119.0

[8500 rows x 4 columns]

In [ ]:
df_cas = pd.get_dummies(df_melt)
df_cas

,variable_Category,variable_Lifetime Engaged Users,variable_Lifetime People who have liked your Page and engaged with your post,variable_Lifetime Post Consumers,variable_Lifetime Post Consumptions,variable_Lifetime Post Impressions by people who have liked your Page,variable_Lifetime Post Total Impressions,variable_Lifetime Post Total Reach,variable_Lifetime Post reach by people who like your Page,variable_Page total likes,...,value_457509,value_497910,value_648611,value_665792,value_1107833,value_1110282,value_Link,value_Photo,value_Status,value_Video
0,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False